### ISSUE TITLE
How to sort nodes based on cluster density

### ISSUE THREAD

**Issue by karthikkrishnanv** [CoAxLab/DeBaCl#60]
I am trying this for the first time, so could've missed it. Is there a method available to sort the nodes based on cluster density ?

**Comment by papayawarrior** [comment]
HI @karthikkrishnanv,
There isn't a dedicated method for this, but you can get the start and end density levels of each node in a list and sort with the Python built-in. Suppose we have LST `tree`:

```python
start_levels = {id: node.start_level for id, node in tree.nodes.items()}
sorted_ids = sorted(start_levels, key=start_levels.get)
```
